#!/bin/bash

#######################################################################################
# This will run all ONETEP quality-check (QC) tests on one core on the local machine. #
#######################################################################################
# Written on 2010.10.04 by Jacek Dziedzic (jd12g09@soton.ac.uk).                      #
# v1.00                                                                               #
#######################################################################################

exedir="../bin"

# Count the available ONETEP executables
nexes=`find $exedir -type f -and -perm /110 2>/dev/null | grep -cvE "/arch\$"`

# Abort if there are none
if [ $nexes -eq 0 ]; then
  echo "Could not find any ONETEP executables in $exedir. Aborting!" >&2
  exit 1
fi

# Allow the user to choose if there are more than one
n=1
if [ $nexes -gt 1 ]; then
  echo "There appears to be more than one ONETEP executable in $exedir."
  while [ -z "$user_is_cooperative" ]; do
    echo "Pick an executable to use from the list below by typing a number and pressing ENTER."
    find $exedir -type f -and -perm /110 2>/dev/null | grep -vE "/arch\$" | cat -n
    read n
    if [ $n -lt 1 ] || [ $n -gt $nexes ]; then 
      user_is_cooperative=""
    else
      user_is_cooperative="yes"
    fi
  done
fi

# Pick the executable chosen by the user (or the only executable, if there's one)
exe=`find $exedir -type f -and -perm /110 2>/dev/null | grep -vE "/arch\$" | awk -v n=$n 'NR==n'`

echo "Running quality-check tests with $exe"

if [ ! -x $exe ]; then
  echo "Somehow $exe does not exist or is not executable. Aborting!">&2
  exit 2
fi

for directory in test[0-9]*; do
  echo "Running $directory..."
  cd $directory
  rm -f *.out
  rm -f *.err
  rootname=`echo *.dat | sed "s/\.dat//"`
  cmdline="../$exe $rootname.dat >$rootname.out 2>$rootname.err"
  echo "Executing '$cmdline'"
  echo "in `pwd`"
  echo "Please wait."
  ../$exe $rootname.dat >$rootname.out 2>$rootname.err
  echo "Done. "
  cd - >/dev/null
  echo 
  echo "======================================================================="
done
