#!/bin/bash

INTEL=/opt/intel/Compiler/11.1/072/
MPI=/opt/mpich2/intel/11.1/
MKL=/opt/intel/mkl/11.1/
F90=${MPI}/bin/mpif90
PWD=/tmp/ed/

echo $PWD
echo $F90
echo $MKL
echo $MPI
echo $INTEL

CUDA="-I/usr/local/cuda/include/ -L${PWD}//LIB_GPU_NUMERICS_MAGMA/lib  -L/usr/local/cuda/lib64 -L${PWD}//LIB_GPU_NUMERICS  -L${PWD}//LIB_GPU_NUMERICS_MAGMA/lib  -I${PWD}//LIB_GPU_NUMERICS_MAGMA/include -I${PWD}//LIB_GPU_NUMERICS/MODFILES  -L/usr/local/cuda/lib64 -lgpu -lcudart -lcufft -lcublas -lcuda -lmagma -lmagmablas"
FFLAGS="-fpp -DFFTW3 -DMPI -O3 -ip -no-prec-div -no-prec-sqrt -parallel -openmp -L${MPI}/lib/ -lmpichf90 -lfmpich -lmpich -lmpichcxx -I${MPI}/include/ -I./obj/biggie/ -I. -I../obj/biggie    ${CUDA}  "
LIBS="-L${INTEL}/lib/intel64/  -L${MKL}/lib/em64t/ -lmkl_blas95_lp64 -lmkl_lapack95_lp64 -lmkl_intel_lp64 -lmkl_intel_thread -lmkl_core -liomp5  -L${MPI}/lib/ -lmpichf90 -lfmpich -lmpich -lmpichcxx -I${MPI}/include/ -I${MKL}/include ${CUDA} "
OPTFLAGS="-fpp -DFFTW3 -DMPI -O3 -parallel -openmp -ip -no-prec-div -no-prec-sqrt -DGPU_SPEEDUP_MATMUL_R -DGPU_SPEEDUP_MATMUL -DGPU_SPEEDUP ${CUDA} " 

echo $CUDA
echo $FFLAGS
echo $OPTFLAGS
echo $LIBS
 
FILES21=dmft/onetep.dmft.compute.optics.f90

${F90} -o dmft/onetep.dmft.compute.optics_gpu.out  ${FFLAGS} ${FILES21} ${LIBS} ${OPTFLAGS} 


