MODULE Lanczos_Cullum_levec

  USE Lanczos_Cullum_lesub
  USE Lanczos_Cullum_leval 


  IMPLICIT NONE


  REAL(DBL),  PARAMETER, PRIVATE :: zero=0.0_DBL,one=1.0_DBL,two=2.0_DBL,three=3.0_DBL,four=4.0_DBL
  LOGICAL,    PARAMETER, PRIVATE :: F=.FALSE.,T=.TRUE.


  ! HLEVEC PARAMETERS
  INTEGER,               PRIVATE :: MBETA_,NTVCON_,SVTVEC_,IREAD_,N_,MDIMRV_,MDIMTV_
  INTEGER,               PRIVATE :: TVSTOP_,LVCONT_,ERCONT_,IWRITE_,MATNO_,MBOUND_
  REAL(8),               PRIVATE :: RELTOL_


  ! EIGENVECTORS
  REAL(8), ALLOCATABLE,  PRIVATE :: RITVEC(:)

  INTEGER,PRIVATE                :: UNIT2_,UNIT3_,UNIT4_,UNIT5_,UNIT10_


CONTAINS


!**************************************************************************
!**************************************************************************
!**************************************************************************
!**************************************************************************
!**************************************************************************
!**************************************************************************
!**************************************************************************
!**************************************************************************

  SUBROUTINE init_Lanczos_Cullum_levec
    MBETA_  = 10000 ! ALWAYS FINE 
    MBOUND_ = 0     ! WE WILL GUESS MDIMTV BEFOREHAND...
    MDIMTV_ = 10000 ! ... BUT IT MAYBE WRONG
    NTVCON_ = 0
    SVTVEC_ = 0
    IREAD_  = 1
    TVSTOP_ = 0
    LVCONT_ = 1
    ERCONT_ = 1
    IWRITE_ = 0
    MATNO_  = 1
    RELTOL_ = 10.0_DBL*tolerance
  END SUBROUTINE


!**************************************************************************
!**************************************************************************
!**************************************************************************
!**************************************************************************
!**************************************************************************
!**************************************************************************
!**************************************************************************
!**************************************************************************


  SUBROUTINE find_eigenvec_r(FILE2,FILE3,FILE4,FILE5,FILE10,lowest)
    INTEGER                             :: ZESEED(ran_siz())
    CHARACTER(LEN=*),     INTENT(IN)    :: FILE2,FILE3,FILE4,FILE5,FILE10
    TYPE(eigenlist_type), INTENT(INOUT) :: lowest
    INTEGER                             :: Nlowest,ieigen,m1,m2,ma
    REAL(DBL)                           :: ev

    call build_seed_and_shot_in_genran(ZESEED,iseed)

    N_      =  dimen_H()
    Nlowest =  COUNT(lowest%eigen(:)%converged) ! EIGENVALUES OUTSIDE THE WINDOW WERE FLAGGED OUT
    MDIMRV_ =  Nlowest*N_

    ALLOCATE(RITVEC(MDIMRV_))
 
    ! THIS GENERATES ON THE FLY THE CORRECT INPUT FILE 'FILE5'
 
    CALL open_safe(UNIT5_,FILE5,'UNKNOWN',get_unit=.true.)
    if(rank==0) WRITE(UNIT5_,'(a)') "LEVEC REAL SYMMETRIC EIGENVECTOR COMPUTATIONS, NO REORTHOGONALIZATION"
    if(rank==0) WRITE(UNIT5_,'(a)') "        MDIMTV    MDIMRV  MBETA (MAX.DIMENSIONS OF TVEC, RITVEC AND BETA)"
    if(rank==0) WRITE(UNIT5_,'(3I12)') MDIMTV_,MDIMRV_,MBETA_ 
    if(rank==0) WRITE(UNIT5_,'(a)') "             RELTOL"
    if(rank==0) WRITE(UNIT5_,'(E20.12)') RELTOL_
    if(rank==0) WRITE(UNIT5_,'(a)') "        MBOUND   NTVCON SVTVEC IREAD (FLAGS)"
    if(rank==0) WRITE(UNIT5_,'(4I12)')  MBOUND_,NTVCON_,SVTVEC_,IREAD_
    if(rank==0) WRITE(UNIT5_,'(a)') "        TVSTOP   LVCONT ERCONT  IWRITE (FLAGS)"
    if(rank==0) WRITE(UNIT5_,'(4I12)') TVSTOP_,LVCONT_,ERCONT_,IWRITE_
    if(rank==0) WRITE(UNIT5_,'(a)') "        SEEDSIZE"
    if(rank==0) WRITE(UNIT5_,'(I12)') SIZE(ZESEED)
    if(rank==0) WRITE(UNIT5_,'(a)') "          RHSEED  (RANDOM GENERATOR SEED FOR STARTING VECTOR IN INVERM)"
    if(rank==0) WRITE(UNIT5_,*) ZESEED
    if(rank==0) WRITE(UNIT5_,'(a)') "        MATNO      N"
    if(rank==0) WRITE(UNIT5_,'(2I12)') MATNO_,N_
    CALL close_safe(UNIT5_)

    ! RUN LEVEC 

    call mpibarrier
    CALL levec(FILE2=FILE2,FILE3=FILE3,FILE4=FILE4,FILE5=FILE5,FILE10=FILE10,SILENT=F,Nlowest=Nlowest)
    call mpibarrier

    ! SAVE OUTPUT EIGENPAIRS

    DO ieigen=1,Nlowest
      lowest%eigen(ieigen)%vec%rc = RITVEC((ieigen-1)+1:(ieigen-1)+N_)
    ENDDO

    if(allocated(RITVEC)) DEALLOCATE(RITVEC)

  END SUBROUTINE


!**************************************************************************
!**************************************************************************
!**************************************************************************
!**************************************************************************
!**************************************************************************
!**************************************************************************
!**************************************************************************
!**************************************************************************

  SUBROUTINE levec(FILE2,FILE3,FILE4,FILE5,FILE10,SILENT,Nlowest)
    LOGICAL,          OPTIONAL, INTENT(IN) :: SILENT
    CHARACTER(LEN=*), OPTIONAL, INTENT(IN) :: FILE2,FILE3,FILE4,FILE5,FILE10
    LOGICAL                                :: silent_

    !-----LEVEC (EIGENVECTORS OF REAL SYMMETRIC MATRICES)-------------------
    !
    !     CONTAINS MAIN PROGRAM FOR COMPUTING AN EIGENVECTOR CORRESPONDING
    !     TO EACH OF A SET OF EIGENVALUES WHICH HAVE BEEN COMPUTED
    !     ACCURATELY BY THE CORRESPONDING LANCZOS EIGENVALUE PROGRAM
    !     (LEVAL) FOR REAL SYMMETRIC MATRICES.  THIS PROGRAM COULD BE
    !     MODIFIED TO COMPUTE ADDITIONAL EIGENVECTORS FOR ANY EIGENVALUE
    !     WHICH IS A MULTIPLE EIGENVALUE OF THE GIVEN A-MATRIX.  THE
    !     AMOUNT OF ADDITIONAL COMPUTATION REQUIRED WOULD DEPEND UPON
    !     THE GIVEN A-MATRIX AND UPON WHAT PART OF THE SPECTRUM OF
    !     A IS INVOLVED.
    !
    !     THE LANCZOS EIGENVECTOR COMPUTATIONS ASSUME THAT EACH
    !     EIGENVALUE THAT IS BEING CONSIDERED HAS CONVERGED AS AN
    !     EIGENVALUE OF THE LANCZOS TRIDIAGONAL MATRICES.
    !
    !     PFORT VERIFIER IDENTIFIED THE FOLLOWING NONPORTABLE
    !     CONSTRUCTIONS
    !
    !     1.  DATA/MACHEP/ STATEMENT
    !     2.  ALL READ(UNIT5_,*) STATEMENTS (FREE FORMAT)
    !     3.  FORMAT(20A4) USED WITH THE EXPLANATORY HEADER, EXPLAN
    !     4.  HEXADECIMAL FORMAT (4Z20) USED IN ALPHA/BETA FILES 1 AND 2.
    !
    !     IMPORTANT NOTE:  THIS PROGRAM ALLOWS ENLARGEMENT OF THE ALPHA,
    !     BETA ARRAYS.  IN PARTICULAR, IF ANY ONE OF THE EIGENVALUES
    !     SUPPLIED IS T-SIMPLE AND NOT CLOSE TO A SPURIOUS EIGENVALUE,
    !     THE PROGRAM REQUIRES THAT KMAX BE AT LEAST 11*MEV/8 + 12.  IF
    !     KMAX IS NOT THIS LARGE, THEN THE PROGRAM RESETS KMAX TO THIS
    !     SIZE AND EXTENDS THE ALPHA, BETA HISTORY IF REQUIRED.
    !     THUS, THE DIMENSIONS OF THE ALPHA AND BETA ARRAYS MUST BE
    !     LARGE ENOUGH TO ALLOW FOR THIS POSSIBILITY.
    !     REMEMBER THAT THE BETA ARRAY, BETA(J), IS SUCH THAT
    !     J = 1,..., KMAX+1.  SO IF THE KMAX USED BY THE PROGRAM
    !     IS TO BE 3000, THEN BETA MUST BE OF LENGTH AT LEAST 3001.
    !
    !-----------------------------------------------------------------------

    REAL(8), ALLOCATABLE          :: V1(:),V2(:)
    REAL(8), ALLOCATABLE          :: ALPHA(:),BETA(:),TVEC(:)
    REAL(8), ALLOCATABLE          :: GOODEV(:),EVNEW(:),TLAST(:)
    REAL(8), ALLOCATABLE          :: G(:)
    REAL,    ALLOCATABLE          :: AMINGP(:),TMINGP(:)
    REAL,    ALLOCATABLE          :: TERR(:),ERR(:),ERRDGP(:),RNORM(:),TBETA(:)
    INTEGER, ALLOCATABLE          :: MP(:),M1(:),M2(:),MA(:),ML(:),MINT(:),MFIN(:)
    INTEGER, ALLOCATABLE          :: IDELTA(:)
    INTEGER, ALLOCATABLE          :: SVSEED(:),SVSOLD(:),RHSEED(:),RHSOLD(:),IIX(:),IIL(:)
    REAL(8)                       :: EVAL,EVALN,TOLN,TTOL,ERTOL,ALFA,BATA
    REAL(8)                       :: MULTOL,SCALE0,STUTOL,BTOL,LB,UB
    REAL(8)                       :: ONE,ZERO,MACHEP,EPSM,TEMP,SUM,ERRMIN,BKMIN
    REAL(8)                       :: RELTOL,ERROR,TERROR!,TLAST(50)
    REAL                          :: EXPLAN(20)
    INTEGER                       :: seedsize,readi1,readi2,readi3,readi4
    INTEGER, ALLOCATABLE          :: readtabi(:)
    REAL(8)                       :: readf1
    INTEGER                       :: MBOUND,NTVCON,SVTVEC,TVSTOP,LVCONT,ERCONT,TFLAG,NGOOD,IT,KINT,KMAXU1,JJ,IC,NGOODC,I,IVEC,LL,LFIN     
    INTEGER                       :: MBETA,IREAD,N,MDIMRV,MDIMTV,J,KMAX,MTOL,NTVEC,ILCOUNT,ILBIS,ICOUNT,MT,KI,KF,MREJEC,K,NACT 
    INTEGER                       :: MREJET,II,KK,LINT,ITEST,NCOMPU,KMAXU,MABEST,NVT,MOLD1,KMAX1,KMAXN,MAMAX,NEVT,NISO,ITEMP,MK1,MK2    
    INTEGER                       :: MATNO ,NMAX,IB,NDIS  ,MPMIN ,IWRITE,MEV ,MOLD,NOLD  ,MATOLD , IBMT 
    REAL                          :: GAP
    INTEGER                       :: Nlowest

    silent_ = T
    IF(PRESENT(SILENT)) silent_ = SILENT

    IF(PRESENT(FILE2))  THEN; CALL OPEN_SAFE(UNIT2_, FILE2,'UNKNOWN',get_unit=.true.);  ENDIF
    IF(PRESENT(FILE3))  THEN; CALL OPEN_SAFE(UNIT3_, FILE3,'UNKNOWN',get_unit=.true.);  ENDIF
    IF(PRESENT(FILE4))  THEN; CALL OPEN_SAFE(UNIT4_, FILE4,'UNKNOWN',get_unit=.true.);  ENDIF
    IF(PRESENT(FILE5))  THEN; CALL OPEN_SAFE(UNIT5_, FILE5,'UNKNOWN',get_unit=.true.);  ENDIF
    IF(PRESENT(FILE10)) THEN; CALL OPEN_SAFE(UNIT10_,FILE10,'UNKNOWN',get_unit=.true.); ENDIF

    !-----------------------------------------------------------------------
    EPSM = 2.0D0*epsilon(RELTOL)
    !-----------------------------------------------------------------------
    !
    !     ARRAYS MUST BE DIMENSIONED AS FOLLOWS:
    !     1.  ALPHA:  >= KMAXN,  BETA: >= (KMAXN+1) WHERE KMAXN, THE
    !                LARGEST SIZE T-MATRIX CONSIDERED BY THE PROGRAM,
    !                IS THE LARGER OF THE SIZE OF THE ALPHA, BETA HISTORY
    !                PROVIDED ON FILE 2 (IF ANY ) AND THE SIZE WHICH THE
    !                PROGRAM SPECIFIES INTERNALLY, THIS LATTER IS ALWAYS
    !                < = 11*MEV / 8  +  12, WHERE MEV IS THE SIZE
    !                T-MATRIX THAT WAS USED IN THE CORRESPONDING EIGENVALUE
    !                COMPUTATIONS.
    !     2.  V1:  >= MAX(N,KMAX)
    !     3.  V2:   >= N
    !     4.  G:  >= MAX(N,KMAX)
    !     5.  RITVEC:  >= N*NGOOD, WHERE NGOOD IS NUMBER OF EIGENVALUES
    !                  SUPPLIED TO THIS PROGRAM.
    !     6.  TVEC:  >= CUMULATIVE LENGTH OF ALL THE T-EIGENVECTORS
    !         NEEDED TO GENERATE THE DESIRED RITZ VECTORS.  AN EDUCATED
    !         GUESS AT AN APPROPRIATE LENGTH CAN BE OBTAINED BY RUNNING THE
    !         PROGRAM WITH THE FLAG MBOUND = 1 AND MULTIPLYING THE
    !         RESULTING SIZE BY 5/4.
    !     7.  GOODEV, AMINGP, TMINGP, TERR, ERR, ERRGDP, RNORM, TBETA,
    !         TLAST, EVNEW, MP, MA, M1, M2, MINT, MFIN AND IDELTA ALL MUST
    !         BE >= NGOOD.
    !
    !-----------------------------------------------------------------------
    !     OUTPUT HEADER
    IF(.NOT.silent_) WRITE(6,10)
    10 FORMAT(/' LANCZOS EIGENVECTOR PROCEDURE FOR REAL SYMMETRIC MATRICES'/)
    !
    !     SET PROGRAM PARAMETERS
    !     USER MUST NOT MODIFY SCALE0
    SCALE0 = 5.0D0; ZERO = 0.0D0; ONE = 1.0D0; MPMIN = -1000
    !     SET CONVERGENCE CRITERION FOR T-EIGENVECTORS.
    ERTOL = 1.D-10
    !
    !     READ USER-SPECIFIED PARAMETER FROM INPUT FILE 5 (FREE FORMAT)
    !
    !     READ USER-PROVIDED HEADER FOR RUN
    READ(UNIT5_,20) EXPLAN
    IF(.NOT.silent_) WRITE(6,20) EXPLAN
    20 FORMAT(20A4)
    !
    !     READ IN THE MAXIMUM PERMISSIBLE DIMENSIONS FOR THE TVEC ARRAY
    !     (MDIMTV), FOR THE RITVEC ARRAY (MDIMRV), AND FOR THE BETA
    !     ARRAY (MBETA).
    READ(UNIT5_,20) EXPLAN
    READ(UNIT5_,*) MDIMTV, MDIMRV, MBETA
    !
    ! THIS IS THE PLACE TO ALLOCATE ARRAY TVEC
    !
    if(allocated(TVEC)) deallocate(TVEC)
    ALLOCATE(TVEC(MDIMTV))
    !
    !     READ IN RELATIVE TOLERANCE (RELTOL) USED IN DETERMINING
    !     APPROPRIATE SIZES FOR THE T-MATRICES TO BE USED IN THE RITZ
    !     VECTOR COMPUTATIONS.
    READ(UNIT5_,20) EXPLAN
    READ(UNIT5_,*) RELTOL
    !
    !     SET FLAGS TO 0 OR 1:
    !     MBOUND = 1:  PROGRAM TERMINATES AFTER COMPUTING 1ST GUESSES
    !                  ON APPROPRIATE T-SIZES FOR USE IN THE RITZ VECTOR
    !                  COMPUTATIONS
    !     NTVCON = 0:  PROGRAM TERMINATES IF THE TVEC ARRAY IS NOT
    !                  LARGE ENOUGH TO HOLD ALL THE T-EIGENVECTORS REQUIRED.
    !     SVTVEC = 0:  THE T-EIGENVECTORS ARE NOT WRITTEN TO FILE 11
    !                  UNLESS TVSTOP = 1
    !     SVTVEC = 1:  WRITE THE T-EIGENVECTORS TO FILE 11.
    !     TVSTOP = 1:  PROGRAM TERMINATES AFTER COMPUTING THE
    !                  T-EIGENVECTORS
    !     LVCONT = 0:  PROGRAM TERMINATES IF THE NUMBER OF T-EIGENVECTORS
    !                  COMPUTED IS NOT EQUAL TO THE NUMBER OF RITZ
    !                  VECTORS REQUESTED.
    !     ERCONT = 0:  MEANS FOR ANY GIVEN EIGENVALUE, A RITZ VECTOR
    !                  WILL NOT BE COMPUTED FOR THAT EIGENVALUE UNLESS
    !                  A T-EIGENVECTOR HAS BEEN IDENTIFIED WITH A LAST
    !                  COMPONENT WHICH SATISFIES THE SPECIFIED
    !                  CONVERGENCE CRITERION.
    !     ERCONT = 1:  MEANS FOR ANY GIVEN EIGENVALUE, A RITZ VECTOR
    !                  WILL BE COMPUTED.  IF A T-EIGENVECTOR CANNOT
    !                  BE IDENTIFIED WHICH SATISFIES THE LAST
    !                  COMPONENT CRITERION, THEN THE PROGRAM WILL
    !                  USE THE T-VECTOR THAT CAME CLOSEST TO
    !                  SATISFYING THE CRITERION.
    !     IWRITE = 1:  EXTENDED OUTPUT OF INTERMEDIATE COMPUTATIONS
    !                  IS WRITTEN TO FILE 6
    !     IREAD = 0:   ALPHA/BETA FILE IS REGENERATED.
    !     IREAD = 1:   ALPHA/BETA FILE USED IN EIGENVALUE COMPUTATIONS
    !                  IS READ IN AND EXTENDED IF NECESSARY.  IN BOTH
    !                  CASES IREAD = 0 OR 1, THE LANCZOS VECTORS ARE
    !                  ALWAYS REGENERATED FOR THE RITZ VECTOR
    !                  COMPUTATIONS
    !
    READ(UNIT5_,20) EXPLAN
    READ(UNIT5_,*) MBOUND,NTVCON,SVTVEC,IREAD
    !
    READ(UNIT5_,20) EXPLAN
    READ(UNIT5_,*) TVSTOP,LVCONT,ERCONT,IWRITE
    IF (TVSTOP.EQ.1) SVTVEC = 1
    !
    !     READ IN SEED (RHSEED) FOR GENERATING RANDOM STARTING VECTOR
    !     FOR INVERSE ITERATION ON THE T-MATRICES.
    READ(UNIT5_,20) EXPLAN
    READ(UNIT5_,*) seedsize
    !
    ! THIS IS THE PLACE TO ALLOCATE RHSEED
    !
    if(allocated(rhseed)) deallocate(rhseed)
    ALLOCATE(RHSEED(seedsize))
    READ(UNIT5_,20) EXPLAN
    READ(UNIT5_,*) RHSEED
    !
    !     READ IN MATNO = MATRIX/RUN IDENTIFICATION NUMBER AND
    !     N = ORDER OF A-MATRIX
    READ(UNIT5_,20) EXPLAN
    READ(UNIT5_,*) MATNO,N
    !
    !-----------------------------------------------------------------------
    !     WRITE RUN PARAMETERS OUT TO FILE 6
    !
    IF(.NOT.silent_) WRITE(6,30) MATNO,N
    30 FORMAT(/' MATRIX IDENTIFICATION NO. = ',I10,' ORDER OF A = ',I12)
    !
    IF(.NOT.silent_) WRITE(6,40) MBOUND,NTVCON,SVTVEC,IREAD
    40 FORMAT(/3X,'MBOUND',3X,'NTVCON',3X,'SVTVEC',3X,'IREAD'/3I9,I8)
    !
    IF(.NOT.silent_) WRITE(6,50) TVSTOP,LVCONT,ERCONT,IWRITE
    50 FORMAT(/3X,'TVSTOP',3X,'LVCONT',3X,'ERCONT',3X,'IWRITE'/4I9)
    !
    IF(.NOT.silent_) WRITE(6,60) MDIMTV,MDIMRV,MBETA
    60 FORMAT(/3X,'MDIMTV',3X,'MDIMRV',3X,'MBETA'/2I9,I8)
    !
    !IF(.NOT.silent_) WRITE(6,70) RELTOL,RHSEED
    !70 FORMAT(/7X,'RELTOL',3X,'RHSEED'/E13.4,I9)
    IF(.NOT.silent_) WRITE(6,70) RELTOL
    70 FORMAT(/7X,'RELTOL'/E13.4)
    IF(.NOT.silent_) WRITE(6,71)
    71 FORMAT(/7X,'RHSEED'/)
    IF(.NOT.silent_) WRITE(6,*) RHSEED

    !     FROM FILE 3 READ IN THE NUMBER OF EIGENVALUES (NGOOD) FOR WHICH
    !     EIGENVECTORS ARE REQUESTED, THE ORDER (MEV) OF THE LANCZOS
    !     TRIDIAGONAL MATRIX USED IN COMPUTING THESE EIGENVALUES, THE
    !     ORDER (NOLD) OF THE USER-SPECIFIED MATRIX USED IN THE EIGENVALUE
    !     COMPUTATIONS, THE SEED (SVSEED) USED FOR GENERATING THE STARTING
    !     VECTOR THAT WAS USED IN THOSE LANCZOS EIGENVALUE COMPUTATIONS,
    !     AND THE MATRIX/RUN IDENTIFICATION NUMBER (MATOLD) USED IN THOSE
    !     COMPUTATIONS.  ALSO READ IN THE NUMBER (NDIS) OF DISTINCT
    !     EIGENVALUES OF T(1,MEV) THAT WERE COMPUTED BUT THIS VALUE IS
    !     NOT USED IN THE EIGENVECTOR COMPUTATIONS.

    READ(UNIT3_,80) NGOOD,NDIS,MEV,NOLD,MATOLD
    80 FORMAT(3I6,I12,I8)

    NGOOD=min(Nlowest,NGOOD)


    ! THIS IS THE PLACE TO ALLOCATE SOME MORE ARRAYS

    write(*,*) 'cullum levec allocate arrays'
    ALLOCATE(GOODEV(NGOOD),EVNEW(NGOOD),AMINGP(NGOOD),TMINGP(NGOOD))
    ALLOCATE(TERR(NGOOD),ERR(NGOOD),ERRDGP(NGOOD),RNORM(NGOOD))
    ALLOCATE(TBETA(NGOOD),TLAST(NGOOD),MP(NGOOD),MA(NGOOD),M1(NGOOD),ML(NGOOD))
    ALLOCATE(M2(NGOOD),MINT(NGOOD),MFIN(NGOOD),IDELTA(NGOOD))
    !
    write(*,*) '...done...'
    READ(UNIT3_,81) seedsize
    81 FORMAT(I12)
    !
    ! THIS THE PLACE TO ALLOCATE SVSEED AND IIX AND IIL
    !
    if(allocated(svseed)) deallocate(svseed)
    ALLOCATE(SVSEED(seedsize),IIX(seedsize),IIL(seedsize))
    READ(UNIT3_,20) EXPLAN
    READ(UNIT3_,*) SVSEED
    !
    !     READ IN THE T-MULTIPLICITY TOLERANCE USED IN THE BISEC SUBROUTINE
    !     DURING THE COMPUTATION OF THE GIVEN EIGENVALUES.
    !     ALSO READ IN THE FLAG IB.  IF IB < 0, THEN SOME BETA(I) IN THE
    !     T-MATRIX FILE PROVIDED ON FILE 2 FAILED THE ORTHOGONALITY
    !     TEST IN THE TNORM SUBROUTINE.  USER SHOULD NOTE THAT THIS VECTOR
    !     PROGRAM PROCEEDS INDEPENDENTLY OF THE SIZE OF THE BETA USED.

    READ(UNIT3_,90) MULTOL,IB,BTOL
    90 FORMAT(E20.12,I6,E13.4)

    TEMP = DBLE(MEV+1000)
    TTOL = MULTOL/TEMP
    IF(.NOT.silent_) WRITE(6,100) MULTOL,TTOL
    100 FORMAT(/' T-MULTIPLICITY TOLERANCE USED IN THE EIGENVALUE COMPUTATIONS WAS',E13.4/&
    ' SCALED MACHINE EPSILON IS',E13.4)

    !     CONTINUE WRITE TO FILE 6 OF THE PARAMETERS FOR THIS RUN


    IF(.NOT.silent_) WRITE(6,110) NGOOD,NDIS,MEV,NOLD,MATOLD
    110 FORMAT(/' EIGENVALUES SUPPLIED ARE READ IN FROM FILE 3'/' FILE 3 HEADER IS'/&
    4X,'NG',2X,'NDIS',3X,'MEV',2X,'NOLD',2X,'MATOLD',4X/&
    3I6,I12,I8/)
    IF(.NOT.silent_) WRITE(6,111) seedsize
    111 FORMAT(/4X,'seedsize'/I12/)
    IF(.NOT.silent_) WRITE(6,112)
    112 FORMAT(/4X,'SVSEED'/)
    IF(.NOT.silent_) WRITE(6,*) SVSEED


    !     IS THE ARRAY RITVEC LONG ENOUGH TO HOLD ALL OF THE DESIRED
    !     RITZ VECTORS (APPROXIMATE EIGENVECTORS)?

    NMAX = NGOOD*N
    IF(MBOUND.NE.0) GO TO 120
    IF(TVSTOP.NE.1.AND.NMAX.GT.MDIMRV) GO TO 1310

    !
    !     CHECK THAT THE ORDER N AND THE MATRIX IDENTIFICATION NUMBER
    !     MATNO SPECIFIED BY THE USER AGREE WITH THOSE READ IN FROM
    !     FILE 3.
    120 ITEMP = (NOLD-N)**2+(MATOLD-MATNO)**2
    IF (ITEMP.NE.0) GO TO 1330



    !     READ IN FROM FILE 3, THE T-MULTIPLICITIES OF THE EIGENVALUES
    !     WHOSE EIGENVECTORS ARE TO BE COMPUTED, THE VALUES OF THESE
    !     EIGENVALUES AND THEIR MINIMAL GAPS AS EIGENVALUES OF THE
    !     USER-SPECIFIED MATRIX AND AS EIGENVALUES OF THE T-MATRIX.

    READ(UNIT3_,20) EXPLAN
    READ(UNIT3_,130) (MP(J),GOODEV(J),TMINGP(J),AMINGP(J), J=1,NGOOD)
    130 FORMAT(6X,I6,E25.16,2E14.3)

    !
    IF(.NOT.silent_) WRITE(6,140) (J,GOODEV(J),MP(J),TMINGP(J),AMINGP(J), J=1,NGOOD)
    140 FORMAT(/' EIGENVALUES READ IN, T-MULTIPLICITIES, T-GAPS AND A-GAPS'/&
    4X,' J ',5X,'GOOD EIGENVALUE',5X,'MULT',4X,'  TMINGAP ',4X,'  AMINGAP '/(I6,E25.16,I4,2E15.4))


    !     READ IN ERROR ESTIMATES
    IF(.NOT.silent_) WRITE(6,150) MEV
    150 FORMAT(/' THESE EIGENVALUES WERE COMPUTED USING A T-MATRIX OF ORDER ',I5/)
    IF(.NOT.silent_) WRITE(6,151)
    151 FORMAT(' AND SEED FOR RANDOM NUMBER GENERATOR ='/)
    IF(.NOT.silent_) WRITE(6,*) SVSEED
    !     CHECK WHETHER OR NOT THERE ARE ANY T-ISOLATED EIGENVALUES IN
    !     THE EIGENVALUES PROVIDED
    DO 160 J=1,NGOOD
      IF(MP(J).EQ.1) GO TO 170
      160 CONTINUE
      GO TO 190
      170 READ(UNIT4_,20) EXPLAN
      READ(UNIT4_,20) EXPLAN
      READ(UNIT4_,20) EXPLAN
      READ(UNIT4_,*) readi1,readi2,readi3,NISO,readi4
      READ(UNIT4_,20) EXPLAN
      READ(UNIT4_,20) EXPLAN
      READ(UNIT4_,20) EXPLAN
      READ(UNIT4_,*) readi1
      IF(ALLOCATED(readtabi)) DEALLOCATE(readtabi)
      ALLOCATE(readtabi(readi1))
      READ(UNIT4_,20) EXPLAN
      READ(UNIT4_,*) readtabi
      READ(UNIT4_,20) EXPLAN
      190 DO 220 J=1,NGOOD

 ERR(J) = 0.D0
 IF(MP(J).NE.1) GO TO 220

 READ(UNIT4_,*) readi1,EVAL,ERR(J),readf1
 IF(DABS(EVAL - GOODEV(J)).LT.1.D-10) GO TO 220
 WRITE(6,210) EVAL,GOODEV(J)
 210 FORMAT(' PROBLEM WITH READ IN OF ERROR ESTIMATES'/&
 ' EIGENVALUE READ IN',E20.12,' DOES NOT MATCH GOODEV(J) ='/E20.12)
 GO TO 1550


 220 CONTINUE
 
 IF(.NOT.silent_) WRITE(6,230) (J,GOODEV(J),ERR(J), J=1,NGOOD)
 230 FORMAT(' ERROR ESTMATES ='/4X,' J',5X,'EIGENVALUE',10X,' ESTIMATE'/(I6,E20.12,E14.3))

 IF(IREAD.EQ.0)  GO TO 330

 !     READ IN THE SIZE OF THE T-MATRIX PROVIDED ON FILE 2.  READ IN
 !     THE ORDER OF THE USER-SPECIFIED MATRIX , THE SEED FOR THE
 !     RANDOM NUMBER GENERATOR, AND THE MATRIX/TEST IDENTIFICATION
 !     NUMBER THAT WERE USED IN THE LANCZOS EIGENVALUE COMPUTATIONS.
 !     THESE ARE USED IN A CONSISTENCY CHECK
 !     IF FLAG IREAD = 0 REGENERATE ALPHA, BETA

 READ(UNIT2_,*) KMAX,NOLD,MATOLD
 READ(UNIT2_,*) seedsize

 ! THIS IS THE PLACE TO ALLOCATE SVSOLD
 
 ALLOCATE(SVSOLD(seedsize))
 READ(UNIT2_,20) EXPLAN
 READ(UNIT2_,*) SVSOLD
 
 IF(.NOT.silent_) WRITE(6,250) KMAX,NOLD,MATOLD
 250 FORMAT(/' READ IN THE T-MATRICES STORED ON FILE 2'/' FILE 2 HEADER IS'/&
 2X,'KMAX',2X,'NOLD',6X,'MATOLD'/3I12)
 IF(.NOT.silent_) WRITE(6,251) seedsize
 251 FORMAT(' seedsize'/I12)
 IF(.NOT.silent_) WRITE(6,252)
 252 FORMAT(' SVSOLD')
 IF(.NOT.silent_) WRITE(6,*) SVSOLD

 !     CHECK THAT THE ORDER, THE MATRIX/TEST IDENTIFICATION NUMBER
 !     AND THE SEED FOR THE RANDOM NUMBER GENERATOR USED IN THE
 !     LANCZOS COMPUTATIONS THAT GENERATED THE ALPHA,BETA FILE
 !     BEING USED AGREE WITH WHAT THE USER HAS SPECIFIED.

 IF (NOLD.NE.N.OR.MATOLD.NE.MATNO.OR.ANY(SVSOLD/=SVSEED)) GO TO 1430

 KMAX1 = KMAX + 1

 ALLOCATE(ALPHA(MAX(KMAX,11*MEV/8+12)))
 ALLOCATE(BETA(SIZE(ALPHA)+1))
 ALLOCATE(V1(MAX(N,KMAX)),V2(MAX(N,KMAX)),G(MAX(N,KMAX)))

 !     READ IN THE T-MATRICES FROM FILE 2.  THESE ARE USED TO GENERATE
 !     THE T-EIGENVECTORS THAT WILL BE USED IN THE RITZ VECTOR
 !     COMPUTATIONS.  HISTORY MUST BE STORED IN MACHINE FORMAT
 !     ((4Z20) FOR IBM/3081)

 READ(UNIT2_,260) (ALPHA(J), J=1,KMAX)
 READ(UNIT2_,260) (BETA(J), J=1,KMAX1)
 260 FORMAT(4Z20)

 READ(UNIT2_,260) (V1(J), J=1,N)
 READ(UNIT2_,260) (V2(J), J=1,N)

 !     KMAX MAY BE ENLARGED IF THE SIZE AT WHICH THE EIGENVALUE
 !     COMPUTATIONS WERE PERFORMED IS ESSENTIALLY KMAX AND
 !     THERE IS AT LEAST ONE EIGENVALUE THAT IS T-SIMPLE AND
 !     T-ISOLATED, IN THE SENSE THAT IF ITS NEAREST NEIGHBOR IS TOO
 !     CLOSE THAT NEIGHBOR IS A 'GOOD' T-EIGENVALUE.

 DO 270 J = 1,NGOOD
   IF(MP(J).EQ.1) GO TO 290
   270 CONTINUE
   IF(.NOT.silent_) WRITE(6,280)
   280 FORMAT(/' ALL EIGENVALUES USED ARE T-MULTIPLE OR CLOSE TO SPURIOUS T-EIGENVALUES'/&
   ' SO KMAX IS NOT INCREASED')
   IF(KMAX.LT.MEV) GO TO 1370
   GO TO 310
 
   290 KMAXN= 11*MEV/8 + 12
   IF(MBETA.LE.KMAXN)  GO TO 1530
   IF(KMAX.GE.KMAXN )  GO TO 310
   IF(.NOT.silent_) WRITE(6,300) KMAX, KMAXN
   300 FORMAT(' ENLARGE KMAX FROM ',I6,' TO ',I6)
   MOLD1 = KMAX + 1
   KMAX  = KMAXN
   GO TO 380

   310 IF(.NOT.silent_) WRITE(6,320) KMAX
   320 FORMAT(/' T-MATRICES HAVE BEEN READ IN FROM FILE 2'/&
   ' THE LARGEST SIZE T-MATRIX ALLOWED IS',I6/)
 
   IF(IREAD.EQ.1) GO TO 400
 
   !     REGENERATE THE ALPHA AND BETA

   330 MOLD1 = 1
 
   DO 340 J = 1,NGOOD
     IF(MP(J).EQ.1) GO TO 360
     340 CONTINUE
     KMAX = MEV + 12
     IF(.NOT.silent_) WRITE(6,350) KMAX
     350 FORMAT(/' ALL EIGENVALUES FOR WHICH EIGENVECTORS ARE TO BE COMPUTED ARE EITHER T-MULTIPLE OR CLOSE TO'/&
     ' A SPURIOUS T-EIGENVALUE. THEREFORE SET KMAX = MEV + 12 = ',I7)
     GO TO 380
     !
     360 KMAXN = 11*MEV/8 + 12
     IF(MBETA.LE.KMAXN) GO TO 1530
     IF(.NOT.silent_) WRITE(6,370) KMAXN
     370 FORMAT(' SET KMAX EQUAL TO ',I6)
     KMAX = KMAXN
     !
     380 IF(.NOT.silent_) WRITE(6,390) MOLD1,KMAX
     390 FORMAT(/' LANCZS SUBROUTINE GENERATES ALPHA(J), BETA(J+1), J =',I6,' TO ', I6/)
     !
     !-----------------------------------------------------------------------
     IIX = SVSEED
     CALL LANCZS_R(MATVEC,ALPHA,BETA,V1,V2,G,KMAX,MOLD1,N,IIX)
     !-----------------------------------------------------------------------
     !
     400 CONTINUE

     !     THE SUBROUTINE STURMI DETERMINES THE SMALLEST SIZE T-MATRIX FOR
     !     WHICH THE EIGENVALUE IN QUESTION IS A T-EIGENVALUE (TO WITHIN A
     !     GIVEN TOLERANCE) AND IF POSSIBLE THE SMALLEST SIZE T-MATRIX
     !     FOR WHICH IT IS A DOUBLE T-EIGENVALUE (TO WITHIN THE SAME
     !     TOLERANCE).  THE SIZE T-MATRIX USED IN THE RITZ VECTOR
     !     COMPUTATIONS IS THEN DETERMINED BY LOOPING ON SIZE OF THE
     !     T-EIGENVECTORS STARTING WITH A T-SIZE DETERMINED FROM THE
     !     OUTPUT FROM STURMI.
 
 
     STUTOL = SCALE0*MULTOL
     IF(IWRITE.EQ.1)THEN; IF(.NOT.silent_) WRITE(6,410); ENDIF
     410 FORMAT(' FROM STURMI')
     DO 450 J = 1,NGOOD
       EVAL = GOODEV(J)
       !     COMPUTE THE TOLERANCES USED BY STURMI TO DETERMINE AN INTERVAL
       !     CONTAINING THE EIGENVALUE EVAL.
       TEMP = DABS(EVAL)*RELTOL
       TOLN = DMAX1(TEMP,STUTOL)

       !-----------------------------------------------------------------------
       CALL STURMI(ALPHA,BETA,EVAL,TOLN,EPSM,KMAX,MK1,MK2,IC,IWRITE,SILENT=silent_)
       !-----------------------------------------------------------------------

       !     STORE THE COMPUTED ORDERS OF T-MATRICES FOR LATER PRINTOUT

       M1(J) = MK1
       M2(J) = MK2
       ML(J) = (MK1 + 3*MK2)/4
       IF(MK2.EQ.KMAX)  ML(J) = KMAX
       !
       IF(IC.GT.0) GO TO 430
       !     IC = 0 MEANS THERE WAS NO EIGENVALUE IN THE DESIGNATED INTERVAL
       !     BY T-SIZE KMAX.  THIS MEANS THAT THE EIGENVALUE PROVIDED HAS
       !     NOT YET CONVERGED SO ITS EIGENVECTOR WILL NOT BE COMPUTED.
       WRITE(6,420) J,GOODEV(J),MK1,MK2
       420 FORMAT(I6,'TH EIGENVALUE',E20.12,' HAS NOT CONVERGED '/&
       ' SO DO NOT COMPUTE ANY T-EIGENVECTOR OR RITZ VECTOR FOR IT'/&
       ' MK1 AND MK2 FOR THIS EIGENVALUE WERE',2I6)
       MP(J) = MPMIN
       MA(J) = -2*KMAX
       GO TO 450
       !     COMPUTE AN APPROPRIATE SIZE T-MATRIX FOR THE GIVEN EIGENVALUE.
       430 IF(M2(J).EQ.KMAX) GO TO 440
       !     M1 AND M2 WERE BOTH DETERMINED
       MA(J) = (3*M1(J) + M2(J))/4  + 1
       GO TO 450
       !     M2 NOT DETERMINED
       440 MA(J) = (5*M1(J))/4  + 1
       !
       450 CONTINUE
       !
       IF (IWRITE.EQ.1)THEN; IF(.NOT.silent_) WRITE(6,460) (MA(JJ), JJ=1,NGOOD); ENDIF
       460 FORMAT(/' 1ST GUESS AT APPROPRIATE SIZE T-MATRICES'/&
       ' ACTUAL VALUES WILL PROBABLY BE 1/4 AGAIN AS MUCH'/(13I6))

       !     PRINT OUT TO FILE 10 1ST GUESSES AT SIZES OF THE T-MATRICES TO
       !     BE USED IN THE EIGENVECTOR COMPUTATIONS.
       !     PROGRAM LOOPS ON T-SIZE TO DETERMINE APPROPRIATE SIZE T-MATRIX.

       if(rank==0) WRITE(UNIT10_,470) N,KMAX
       470 FORMAT(2I8,' = ORDER OF USER MATRIX AND MAX ORDER OF T(1,MEV)')

       if(rank==0) WRITE(UNIT10_,480)
       480 FORMAT(/' 1ST GUESS AT APPROPRIATE SIZE T-MATRICES'/&
       ' ACTUAL VALUES WILL PROBABLY BE 1/4 AGAIN AS MUCH'/)

       if(rank==0) WRITE(UNIT10_,490)
       490 FORMAT(4X,'J',4X,'A-EIGENVALUE',4X,'M1(J)',1X,'M2(J)',1X,'MA(J)')

       if(rank==0) WRITE(UNIT10_,500) (J,GOODEV(J),M1(J),M2(J), MA(J), J=1,NGOOD)
       500 FORMAT(I5,E19.12,3I6)

       IF(MBOUND.EQ.1.and.rank==0) WRITE(UNIT10_,510)
       510 FORMAT(/'  EV = GOODEV(J) IS A GOOD EIGENVALUE OF T(1,MEV)'/&
       ' M1 = SMALLEST VALUE OF M SUCH THAT T(1,M) HAS AT LEAST'/&
       '     ONE EIGENVALUE IN THE INTERVAL (EV-TOLN,EV+TOLN)'/&
       '     TOLN(J) = DMAX1(GOODEV(J)*RELTOL, SCALE0*MULTOL)'/&
       ' M2 = SMALLEST M (IF ANY) SUCH THAT IN THE ABOVE INTERVAL'/&
       '      T(1,M) HAS AT LEAST TWO EIGENVALUES '/&
       ' IABS(MA(J)) = APPROPRIATE SIZE T-MATRIX FOR GOODEV(J)'/&
       ' INITIAL VALUE OF MA(J) IS CHOSEN HEURISTICALLY'/&
       ' PROGRAM LOOPS ON SIZE OF T-MATRIX TO GET BETTER SIZE'/&
       ' END OF SIZES OF T-MATRICES FILE 10'///)

       !     TERMINATE AFTER COMPUTING 1ST GUESSES AT SIZES OF THE
       !     T-MATRICES REQUIRED FOR THE GIVEN EIGENVALUES?
       IF(MBOUND.EQ.1) GO TO 1390

       !     IS THERE ROOM FOR ALL OF THE REQUESTED T-EIGENVECTORS?
       MTOL = 0
       DO 520 J = 1,NGOOD
  IF(MP(J).EQ.MPMIN) GO TO 520
  MTOL = MTOL + IABS(MA(J))
  520 CONTINUE
  MTOL = (5*MTOL)/4
  IF(MTOL.GT.MDIMTV.AND.NTVCON.EQ.0) GO TO 1410

  !-----------------------------------------------------------------------
  !     GENERATE A RANDOM VECTOR TO BE USED REPEATEDLY BY
  !     SUBROUTINE INVERM
  !
  CALL GENRAN(RHSEED,G,KMAX)
  !---------------------------------------------------------------------

  !     LOOP ON GIVEN EIGENVALUES TO COMPUTE THE CORRESPONDING
  !     T-EIGENVECTOR.

  MTOL = 0
  NTVEC = 0
  ILBIS = 0

  DO 710 J = 1,NGOOD
    ICOUNT = 0
    ERRMIN = 10.D0
    MABEST = MPMIN
    IF(MP(J).EQ.MPMIN) GO TO 710
    TFLAG = 0
    EVAL = GOODEV(J)
    TEMP = DABS(EVAL)*RELTOL
    UB = EVAL + DMAX1(STUTOL,TEMP)
    LB = EVAL - DMAX1(STUTOL,TEMP)
    530 KMAXU = IABS(MA(J))

    !     SELECT A SUITABLE INCREMENT FOR THE ORDERS OF THE T-MATRICES
    !     TO BE CONSIDERED IN DETERMINING APPROPRIATE SIZES FOR THE RITZ
    !     VECTOR COMPUTATIONS.
    IF(ICOUNT.GT.0) GO TO 550
    !     SELECT IDELTA(J) BASED UPON THE T-MULTIPLICITY OBTAINED
    IF(M2(J).EQ.KMAX) GO TO 540
    !     M2 DETERMINED
    IDELTA(J) = ((3*M1(J) + 5*M2(J))/8  +  1 - IABS(MA(J)))/10  +  1
    GO TO 550
    !     M2 NOT DETERMINED
    540 MAMAX = MIN0((11*MEV)/8 + 12, (13*M1(J))/8 + 1)
    IDELTA(J) = (MAMAX - IABS(MA(J)))/10  +  1
    550 ICOUNT = ICOUNT + 1
    !
    !-----------------------------------------------------------------------
    !     TO MIMIMIZE THE EFFECT OF THE ONE-SIDED ACCEPTANCE TEST FOR
    !     EIGENVALUES IN THE BISEC SUBROUTINE, RECOMPUTE THE GIVEN
    !     EIGENVALUE AT THE SPECIFIED KMAXU
    !
    CALL LBISEC(ALPHA,BETA,EPSM,EVAL,EVALN,LB,UB,TTOL,KMAXU,NEVT,SILENT=silent_)
    !-----------------------------------------------------------------------
    !
    !     CHECK WHETHER OR NOT GIVEN T-MATRIX HAS AN EIGENVALUE IN THE
    !     SPECIFIED INTERVAL AND IF SO WHAT ITS T-MULTIPLICITY IS.
    !
    IF(NEVT.EQ.1) GO TO 590
    IF(NEVT.NE.0) GO TO 570
    ILBIS = 1
    WRITE(6,560) EVAL,KMAXU
    560 FORMAT(/' PROBLEM ENCOUNTERED IN RECOMPUTATION OF USER-SUPPLIED EIGENVALUE',E20.12/&
    ' THE SIZE T-MATRIX SPECIFIED',I6,' DOES NOT HAVE AN EIGENVALUE IN THE INTERVAL SPECIFIED'/&
    ' THEREFORE NO EIGENVECTOR WILL BE COMPUTED FOR THIS PARTICULAR EIGENVALUE'/)
    GO TO 610
    !
    570 IF(NEVT.GT.1)  WRITE(6,580) EVAL,KMAXU
    580 FORMAT(/' PROBLEM ENCOUNTERED IN RECOMPUTATION OF USER-SUPPLIED EIGENVALUE',E20.12/&
    ' FOR THE SIZE T-MATRIX SPECIFIED =',I6,' THE GIVEN EIGENVALUE IS T-MULTIPLE IN THE INTERVAL SPECIFIED'/&
    ' SOMETHING IS WRONG, THEREFORE NO EIGENVECTOR WILL BE COMPUTED FOR THIS EIGENVALUE'/)
    !
    MP(J) = MPMIN
    MA(J) = -2*KMAX
    GO TO 710
    !
    590 CONTINUE
    ILBIS = 0
    !
    EVNEW(J) = EVALN
    EVAL = EVALN
    MTOL = MTOL+KMAXU

    !     IS THERE ROOM IN TVEC ARRAY FOR THE NEXT T-EIGENVECTOR?
    !     IF NOT, SKIP TO RITZ VECTOR COMPUTATIONS.
    IF (MTOL.GT.MDIMTV) GO TO 720
    !
    IT = 3
    KINT = MTOL - KMAXU +1

    !     RECORD THE BEGINNING AND END OF THE T-EIGENVECTOR BEING COMPUTED
    MINT(J) = KINT
    MFIN(J) = MTOL

    !-----------------------------------------------------------------------
    !     SUBROUTINE INVERM DOES INVERSE ITERATION, I.E. SOLVES
    !     (T(1,KMAXU) - EVAL)*U = RHS  FOR EACH EIGENVALUE TO OBTAIN THE
    !     DESIRED T-EIGENVECTOR.
    !
    IF(IWRITE.EQ.1)THEN;  IF(.NOT.silent_) WRITE(6,600) J; ENDIF
    600 FORMAT(/I6,'TH EIGENVALUE')
    !
    CALL INVERM(ALPHA,BETA,V1,TVEC(KINT:),EVAL,ERROR,TERROR,EPSM,G,KMAXU,IT,IWRITE,SILENT=silent_)
    !
    !-----------------------------------------------------------------------
    !
    TERR(J) = TERROR
    TLAST(J) = ERROR
    KMAXU1 = KMAXU + 1
    TBETA(J) = BETA(KMAXU1)*ERROR
    !
    !     AFTER EACH OF THE T-EIGENVECTORS IS COMPUTED, THE
    !     SIZE OF THE ERROR ESTIMATE, ERROR IS CHECKED.
    !     IF THIS ESTIMATE IS NOT AS SMALL AS DESIRED AND
    !     |MA(J)| < ML(J), PROGRAM ATTEMPTS TO INCREASE THE SIZE OF |MA(J)|
    !     AND REPEAT THE T-EIGENVECTOR COMPUTATIONS.
    !
    IF(ERROR.LT.ERTOL.OR.TFLAG.EQ.1)  GO TO 700
    !
    IF(ERROR.GE.ERRMIN) GO TO 610
    !     LAST COMPONENT IS LESS THAN MINIMAL TO DATE
    ERRMIN = ERROR
    MABEST = MA(J)
    610 CONTINUE
    !
    IF(MA(J).GT.0)  ITEST = MA(J) + IDELTA(J)
    IF(MA(J).LT.0)  ITEST = -(IABS(MA(J)) + IDELTA(J))
    IF(IABS(ITEST).LE.ML(J).AND.ICOUNT.LE.10) GO TO 630
    !     NEW MA(J) IS GREATER THAN MAXIMUM ALLOWED.
    IF(ERCONT.EQ.0.OR.MABEST.EQ.MPMIN) GO TO 650
    TFLAG = 1
    MA(J) = MABEST
    IF(ILBIS.EQ.0)  MTOL = MTOL - KMAXU
    WRITE(6,620) MA(J)
    620 FORMAT(' 10 ORDERS WERE CONSIDERED.  NONE SATISFIED THE ERROR TEST'/&
    ' THEREFORE USE THE BEST ORDER OBTAINED FOR THE EIGENVECTORS',I6)
    GO TO 530
    !
    630 MA(J) = ITEST
    !
    MT = IABS(MA(J))
    IF(IWRITE.EQ.1)THEN; IF(.NOT.silent_) WRITE(6,640)  MT; ENDIF
    640 FORMAT(/' CHANGE SIZE OF T-MATRIX TO ',I6,' RECOMPUTE T-EIGENVECTOR')
    !
    IF(ILBIS.EQ.0)  MTOL = MTOL - KMAXU
    !
    GO TO 530

    !     APPROPRIATE SIZE T-MATRIX WAS NOT OBTAINED

    650 CONTINUE
    if(rank==0) WRITE(UNIT10_,660) J,EVAL,MP(J)
    660 FORMAT(/' ON 10 INCREMENTS NOT ABLE TO IDENTIFY APPROPRIATE SIZE T-MATRIX FOR'/&
    ' EIGENVALUE(',I4,') = ',E20.12,' T-MULTIPLICITY =',I4/)
    IF(M2(J).EQ.KMAX.and.rank==0) WRITE(UNIT10_,670)
    IF(M2(J).LT.KMAX.and.rank==0) WRITE(UNIT10_,680)
    670 FORMAT(/' ORDERS TESTED RANGED FROM 5*M1(J)/4 TO APPROXIMATELY'/&
    '  MIN(11*MEV/8,13*M1(J)/8)'/)
    680 FORMAT(/' ORDERS TESTED RANGED FROM (3*M1(J)+M2(J))/4 TO APPROXIMATELY'/&
    '  (3*M1(J) + 5*M2(J))/8.'/)
    if(rank==0) WRITE(UNIT10_,690)
    690 FORMAT(' ALLOWING LARGER ORDERS FOR THE T-MATRICES MAY RESULT IN SUCCESS'/&
    ' BUT PROBABLY WILL NOT.  PROBLEM IS PROBABLY DUE TO'/&
    ' LACK OF CONVERGENCE OF GIVEN EIGENVALUE, CHECK THE ERROR ESTIMATE'/)
    MP(J) = MPMIN
    IF(ILBIS.EQ.0)  MTOL = MTOL - KMAXU
    GO TO 710
    700 NTVEC = NTVEC + 1
    !
    710 CONTINUE
    NGOODC = NGOOD
    GO TO 740

    !     COME HERE IF THERE IS NOT ENOUGH ROOM FOR ALL OF T-EIGENVECTORS

    720 NGOODC = J-1
    WRITE(6,730)  J, MTOL, MDIMTV
    730 FORMAT(/'  NOT ENOUGH ROOM IN TVEC FOR ',I4,'TH T-VECTOR'/&
    '  T-DIMENSION REQUESTED = ',I6,' BUT TVEC HAS DIMENSION = ',I6/)
    IF(NGOODC.EQ.0)  GO TO 1430
    MTOL = MTOL-KMAXU
    !
    740 CONTINUE

    !     THE LOOP ON T-EIGENVECTOR COMPUTATIONS IS COMPLETE.
    !     WRITE OUT THE SIZE T-MATRICES THAT WILL BE USED FOR
    !     THE RITZ VECTOR COMPUTATIONS.

    if(rank==0) WRITE(UNIT10_,750)
    750 FORMAT(/' SIZES OF T-MATRICES THAT WILL BE USED IN THE RITZ COMPUTATIONS'/5X,'J',16X,'GOODEV(J)',1X,'MA(J)')

    if(rank==0) WRITE(UNIT10_,760)   (J,GOODEV(J),MA(J), J=1,NGOOD)
    760 FORMAT(I6,E25.14,I6)
    if(rank==0) WRITE(UNIT10_,510)

    IF(.NOT.silent_) WRITE(6,770) MTOL
    770 FORMAT(/' THE CUMULATIVE LENGTH OF THE T-EIGENVECTORS IS',I18)

    IF(.NOT.silent_) WRITE(6,780) NTVEC,NGOOD
    780 FORMAT(/I6,' T-EIGENVECTORS OUT OF',I6,' REQUESTED WERE COMPUTED')

    !     SAVE THE T-EIGENVECTORS ON FILE 11?
    IF(TVSTOP.NE.1.AND.SVTVEC.EQ.0) GO TO 840

    WRITE(11,790) NTVEC,MTOL,MATNO,SVSEED
    790 FORMAT(I6,3I12,' = NTVEC,MTOL,MATNO,SVSEED')
    !
    DO 820 J=1,NGOODC
      !     IF MP(J) = MPMIN THEN NO SUITABLE T-EIGENVECTOR IS AVAILABLE
      !     FOR THAT EIGENVALUE.
      IF(MP(J).EQ.MPMIN) WRITE(11,800) J,MA(J),GOODEV(J),MP(J)
      800 FORMAT(2I6,E20.12,I6/' TH EIGVAL,T-SIZE,EVALUE,FLAG,NO EIGVEC')
      IF(MP(J).NE.MPMIN) WRITE(11,810) J,MA(J),GOODEV(J),MP(J)
      810 FORMAT(I6,I6,E20.12,I6/' T-EIGVEC,SIZE T,EVALUE OF A,MP(J)')
      IF(MP(J).EQ.MPMIN) GO TO 820
      KI = MINT(J)
      KF = MFIN(J)
      !
      WRITE(11,260) (TVEC(K), K=KI,KF)
      !
      820 CONTINUE
      !
      IF(TVSTOP.NE.1) GO TO 840
      !
      WRITE(6,830) TVSTOP, NTVEC,NGOOD
      830 FORMAT(/' USER SET TVSTOP = ',I1/&
      ' THEREFORE PROGRAM TERMINATES AFTER T-EIGENVECTOR COMPUTATIONS'/&
      ' T-EIGENVECTORS THAT WERE COMPUTED ARE SAVED ON FILE 11'/&
      I8,' T-EIGENVECTORS WERE COMPUTED OUT OF',I7,' REQUESTED'/)
      !
      GO TO 1550
      !
      840 CONTINUE
      !     IF NOT ABLE TO COMPUTE ALL THE REQUESTED T-EIGENVECTORS,
      !     CONTINUE WITH THE LANCZOS VECTOR COMPUTATIONS ANYWAY?
      IF(NTVEC.NE.NGOOD.AND.LVCONT.EQ.0) GO TO 1450
      !
      !     COMPUTE THE MAXIMUM SIZE OF THE T-MATRIX USED FOR THOSE
      !     EIGENVALUES WITH GOOD ERROR ESTIMATES.
      !
      KMAXU = 0
      DO 850 J = 1,NGOODC
        MT = IABS(MA(J))
        IF(MT.LT.KMAXU.OR.MP(J).EQ.MPMIN) GO TO 850
        KMAXU = MT
        850 CONTINUE
        !
        IF(KMAXU.EQ.0) GO TO 1490
        !
        IF(.NOT.silent_) WRITE(6,860) KMAXU
        860 FORMAT(/I6,' = LARGEST SIZE T-MATRIX TO BE USED IN THE RITZ VECTOR COMPUTATIONS')
        !
        !     COUNT THE NUMBER OF RITZ VECTORS NOT BEING COMPUTED
        MREJEC = 0
        DO 870 J=1,NGOODC
   870 IF(MP(J).EQ.MPMIN)  MREJEC = MREJEC + 1
   MREJET = MREJEC + (NGOOD-NGOODC)
   IF(MREJET.NE.0) WRITE(6,880) MREJET
   880 FORMAT(/' RITZ VECTORS ARE NOT COMPUTED FOR',I6,' OF THE EIGENVALUES'/)
   NACT = NGOODC - MREJEC
   IF(.NOT.silent_) WRITE(6,890) NGOOD,NTVEC,NACT
   890 FORMAT(/I6,' RITZ VECTORS WERE REQUESTED'/I6,' T-EIGENVECTORS WERE COMPUTED'/&
   I6,' RITZ VECTORS WILL BE COMPUTED'/)
   !     CHECK IF THERE ARE ANY RITZ VECTORS TO COMPUTE
   IF(MREJEC.EQ.NGOODC) GO TO 1470

   !     CONTINUE WITH THE LANCZOS VECTOR COMPUTATIONS?
   IF(LVCONT.EQ.0.AND.MREJEC.NE.0) GO TO 1450

   !     NOW COMPUTE THE RITZ VECTORS.  REGENERATE THE
   !     LANCZOS VECTORS.

   DO 900 I = 1,NMAX
     900 RITVEC(I) = ZERO

     !-----------------------------------------------------------------------
     !     REGENERATE THE STARTING VECTOR. THIS MUST BE GENERATED AND
     !     NORMALIZED PRECISELY THE WAY IT WAS DONE IN THE EIGENVALUE
     !     COMPUTATIONS, OTHERWISE THERE WILL BE A MISMATCH BETWEEN
     !     THE T-EIGENVECTORS THAT HAVE BEEN COMPUTED FROM THE T-MATRICES
     !     READ IN FROM FILE 2 AND THE LANCZOS VECTORS THAT ARE
     !     BEING REGENERATED.
     !
     IIL = SVSEED
     CALL GENRAN(IIL,G,N)
     !-----------------------------------------------------------------------

     DO 910 J = 1,N
       910 V2(J) = G(J)

       SUM = DBLE(MPI_DOT_PRODUCT(V2(1:N),V2(1:N)))
       SUM = ONE/DSQRT(SUM)

       DO 920 J = 1,N
         V1(J) = ZERO
         920 V2(J) = V2(J)*SUM
         !
         !     LOOP FOR GENERATING RITZ VECTORS  (IVEC = 1,KMAXU)
         IVEC = 1
         BATA = ZERO
         !
         GO TO 980
         !
         930 CONTINUE

         !     COMPUTE V1 = A*V2 - BATA*V1

         !-----------------------------------------------------------------------
         CALL MATVEC(V2(1:N),V1(1:N),BATA)
         !-----------------------------------------------------------------------

         ALFA = DBLE(MPI_DOT_PRODUCT(V1(1:N),V2(1:N)))
         !
         DO 940 J = 1,N
    940 V1(J) = V1(J)-ALFA*V2(J)
    !
    BATA = DBLE(MPI_DOT_PRODUCT(V1(1:N),V1(1:N)))
    BATA = DSQRT(BATA)
    SUM = ONE/BATA
    !
    TEMP = BETA(IVEC)
    TEMP = DABS(BATA - TEMP)/TEMP
    IF (TEMP.LT.1.0D-10)GO TO 960

    !     THE BETA BEING REGENERATED DO NOT MATCH THE BETA IN FILE 2.
    !     SOMETHING IS WRONG IN THE LANCZOS VECTOR GENERATION.
    !     PROGRAM TERMINATES FOR USER TO CORRECT THE PROBLEM
    !     WHICH MUST BE IN THE STARTING VECTOR GENERATION OR IN
    !     THE MATRIX-VECTOR MULTIPLY SUBROUTINE MATVEC SUPPLIED.
    !     THIS SUBROUTINE MUST BE THE SAME ONE USED IN THE
    !     EIGENVALUE COMPUTATIONS OR A MISMATCH WILL ENSUE.

    WRITE(6,950) IVEC,BATA,BETA(IVEC),TEMP
    950 FORMAT(/2X,'IVEC',16X,'BATA',10X,'BETA(IVEC)',14X,'RELDIF'/I6,3E20.12/&
    ' IN LANCZOS VECTOR REGENERATION THE ENTRIES OF THE TRIDIAGONAL MATRICES BEING'/&
    ' GENERATED ARE NOT THE SAME AS THOSE IN THE MATRIX SUPPLIED ON FILE 2.'/&
    ' THEREFORE SOMETHING IS BEING INITIALIZED OR COMPUTED DIFFERENTLY FROM THE WAY'/&
    ' IT WAS COMPUTED IN THE EIGENVALUE COMPUTATIONS'/&
    ' THE PROGRAM TERMINATES FOR THE USER TO DETERMINE WHAT THE PROBLEM IS'/)
    GO TO 1550
    !
    !
    960 CONTINUE
    DO 970 J = 1,N
      TEMP = SUM*V1(J)
      V1(J) = V2(J)
      970 V2(J) = TEMP
      !
      980 CONTINUE
      !
      LFIN = 0
      DO 1000 J = 1,NGOODC
        LL = LFIN
        LFIN = LFIN + N
        !
        IF(IABS(MA(J)).LT.IVEC.OR.MP(J).EQ.MPMIN) GO TO 1000
        II = IVEC + MINT(J) - 1
        TEMP = TVEC(II)
        !     II IS THE (IVEC)TH COMPONENT OF THE T-EIGENVECTOR CONTAINED
        !     IN TVEC(MINT(J)).
        !
        DO 990 K = 1,N
          LL = LL + 1
          990 RITVEC(LL) = TEMP*V2(K) + RITVEC(LL)
          !
          1000 CONTINUE
          !
          IVEC = IVEC + 1
          IF (IVEC.LE.KMAXU) GO TO 930
          !
          !
          !     RITZVECTOR GENERATION IS COMPLETE. NORMALIZE EACH RITZVECTOR.
          !     NOTE THAT IF CERTAIN RITZ VECTORS WERE NOT COMPUTED THEN THAT
          !     PORTION OF THE RITVEC ARRAY WAS NOT UTILIZED.
          !
          LFIN = 0
          DO 1050 J = 1,NGOODC
     !
     KK = LFIN
     LFIN = LFIN + N
     IF(MP(J).EQ.MPMIN) GO TO 1050
     !
     DO 1010 K = 1,N
       KK = KK + 1
       1010 V2(K) = RITVEC(KK)

       SUM = DBLE(MPI_DOT_PRODUCT(V2(1:N),V2(1:N)))
       SUM = DSQRT(SUM)
       RNORM(J) = SUM
       TEMP = DABS(ONE-SUM)
       SUM = ONE/SUM
       !
       KK = LFIN - N
       DO 1020 K = 1,N
         KK = KK + 1
         V2(K) = SUM*V2(K)
         1020 RITVEC(KK) = V2(K)
         !
         IF (IWRITE.NE.0)THEN; IF(.NOT.silent_) WRITE(6,1030) J,GOODEV(J); ENDIF
         1030 FORMAT(/I5,' TH EIGENVALUE CONSIDERED = ',E20.12/)
         !
         IF (IWRITE.NE.0)THEN; IF(.NOT.silent_) WRITE(6,1040) TERR(J),TBETA(J),TEMP; ENDIF
         1040 FORMAT(' NORM OF ERROR IN T-EIGENVECTOR = ',E14.3/&
         ' BETA(MA(J)+1)*U(MA(J)) = ',E14.3/&
         ' ABS(NORM(RITVEC) - 1.0)  = ',E14.3/)
         !
         LINT = LFIN - N + 1
         EVAL = EVNEW(J)
         !
         !-----------------------------------------------------------------------
         CALL MATVEC(RITVEC(LINT:LINT+N-1),V2(1:N),EVAL)
         !-----------------------------------------------------------------------
         !
         !     COMPUTE ERROR IN RITZ VECTOR CONSIDERED AS A EIGENVECTOR OF A.
         !     V2 = A*RITVEC - EVAL*RITVEC

         SUM = DBLE(MPI_DOT_PRODUCT(V2(1:N),V2(1:N)))
         SUM = DSQRT(SUM)
         ERR(J) = SUM
         GAP = ABS(AMINGP(J))
         ERRDGP(J) = SUM/GAP
         !
         1050 CONTINUE

         !
         !     RITZVECTORS ARE NORMALIZED AND ERROR ESTIMATES ARE IN ERR ARRAY
         !     AND IN ERRDGP ARRAY. STORE EVERYTHING
         !

         WRITE(9,1060)
         1060 FORMAT(3X,'A-EIGENVALUE',2X,'MA(J)',3X,'A-MINGAP',6X,'AERROR',2X,'AERROR/GAP',6X,'TERROR')
         !
         WRITE(13,1070)
         1070 FORMAT(16X,'GOODEV(J)',5X,'RITZNORM',6X,'AMINGAP',5X,'TBETA(J)',5X,'TLAST(J)')
         !
         DO 1100 J=1,NGOODC
           !
           IF(MP(J).EQ.MPMIN) GO TO 1100
           !
           WRITE(9,1080)EVNEW(J),MA(J),AMINGP(J),ERR(J),ERRDGP(J),TERR(J)
           1080 FORMAT(E15.8,I6,4E12.4)
           !
           WRITE(13,1090) EVNEW(J),RNORM(J),AMINGP(J),TBETA(J),TLAST(J)
           1090 FORMAT(E25.14,4E13.5)
           !
           1100 CONTINUE
           !
           IF(MREJEC.EQ.0) GO TO 1180
           WRITE(9,1110)
           1110 FORMAT(/' RITZ VECTORS WERE NOT COMPUTED FOR THE FOLLOWING EIGENVALUES'/&
           ' EITHER BECAUSE THEY HAD NOT CONVERGED OR BECAUSE THE ERROR ESTIMATE'/&
           '  WAS NOT AS SMALL AS DESIRED'/)
           !
           DO 1170 J = 1,NGOODC
      IF(MP(J).NE.MPMIN) GO TO 1170
      !     WRITE OUT MESSAGE FOR EACH EIGENVALUE FOR WHICH NO EIGENVECTOR WAS COMPUTED.

      WRITE(9,1120)
      1120 FORMAT(6X,'GOODEV(J)',3X,'MA(J)',5X,'AMINGP(J)',6X,'TLAST(J)',3X,'MP(J)')
      WRITE(9,1130) GOODEV(J),MA(J),AMINGP(J),TBETA(J),MP(J)
      1130 FORMAT(E15.8,I8,2E14.4,I8)

      WRITE(13,1140)
      1140 FORMAT(/' RITZ VECTORS WERE NOT COMPUTED FOR THE FOLLOWING EIGENVALUES'/&
      ' BECAUSE THEY HAD NOT CONVERGED'/)

      WRITE(13,1150)
      1150 FORMAT(6X,'GOODEV(J)',3X,'MA(J)',3X,'M1(J)',3X,'M2(J)',3X,'MP(J)'/)
      WRITE(13,1160) GOODEV(J),MA(J),M1(J),M2(J),MP(J)
      1160 FORMAT(E15.8,4I8)

      1170 CONTINUE
      1180 CONTINUE

      WRITE(9,1190)
      1190 FORMAT(/' ABOVE ARE ERROR ESTIMATES FOR THE A AND T EIGENVECTORS'/&
      ' ASSOCIATED WITH THE GOODEV LISTED IN COLUMN 1'/&
      ' AERROR = NORM(A*X - EV*X)  TERROR = NORM(T*Y - EV*Y) '/&
      ' WHERE T = T(1,MA(J))    X = RITZ VECTOR = V*Y  V = SUCCESSIVE'/&
      ' LANCZOS VECTORS. AMINGAP = GAP TO NEAREST A-EIGENVALUE'//)

      WRITE(13,1200)
      1200 FORMAT(/' ABOVE ARE ERROR ESTIMATES ASSOCIATED WITH THE GOODEV'/&
      ' RITZNORM = NORM(COMPUTED RITZ VECTOR)'/&
      ' TBETA(J) = BETA(MA(J)+1)*Y(MA(J)),  T*Y = EVAL*Y'/&
      ' TLAST(J) = Y(MA(J))'/&
      ' AMINGAP = GAP TO NEAREST A-EIGENVALUE'/)

      !     NUMBER OF RITZ VECTORS COMPUTED
      NCOMPU = NGOODC - MREJEC
      WRITE(12,1210) N,NCOMPU,NGOODC,MATNO
      1210 FORMAT(3I6,I12,' SIZE A, NO.RITZVECS, NO.EVALUES,MATNO')
      !
      LFIN = 0
      DO 1270 J = 1,NGOODC
        LINT = LFIN + 1
        LFIN = LFIN + N

        IF(MP(J).EQ.MPMIN) GO TO 1250

        GO TO 1270
        !     NO RITZ VECTOR WAS COMPUTED FOR THIS EIGENVALUE
        1250 CONTINUE !WRITE(12,1260) J,GOODEV(J),MP(J)

        1270 CONTINUE

        !     DID ANY T-MATRICES INCLUDE OFF-DIAGONAL ENTRIES SMALLER THAN
        !     DESIRED, AS SPECIFIED BY BTOL?

        IF(IB.GT.0) GO TO 1300

        IF(.NOT.silent_) WRITE(6,1280) KMAXU
        1280 FORMAT(/' FOR LARGEST T-MATRIX CONSIDERED',I7,' CHECK THE SIZE OF BETAS')
        !-----------------------------------------------------------------------
        CALL TNORM(ALPHA,BETA,BKMIN,TEMP,KMAXU,IBMT)
        !-----------------------------------------------------------------------

        IF(IBMT.LT.0) WRITE (6,1290)
        1290 FORMAT(/' WARNING THE T-MATRICES FOR ONE OR MORE OF THE EIGENVALUES CONSIDERED'/&
        ' HAD AN OFF-DIAGONAL ENTRY THAT WAS SMALLER THAN THE BETA TOLERANCE THAT WAS SPECIFIED'/)
        1300 CONTINUE
        !
        GO TO 1550
        !
        1310 WRITE(6,1320) NGOOD,NMAX,MDIMRV
        1320 FORMAT(/I4,' RITZ VECTORS WERE REQUESTED BUT THE REQUIRED DIMENSION',I6/&
        ' IS LARGER THAN THE USER-SPECIFIED DIMENSION OF RITVEC',I6/&
        ' THEREFORE, THE EIGENVECTOR PROCEDURE TERMINATES FOR THE USER TO INTERVENE')
        !
        GO TO 1550
        !
        1330 WRITE(6,1340) NOLD,N,MATOLD,MATNO
        1340 FORMAT(//' PARAMETERS READ FROM FILE 3 DO NOT AGREE WITH THOSE SPECIFIED BY THE USER'/&
        ' N,NOLD,MATOLD,MATNO = ',2I6,2I12/' PROGRAM TERMINATES FOR USER TO RESOLVE PROBLEM'/)
        !
        GO TO 1550
        !
        1350 WRITE(6,1360)
        1360 FORMAT(//' PARAMETERS IN THE ALPHA,BETA FILE HEADER DO NOT AGREE WITH PARAMTERS'/&
        ' SPECIFIED BY THE USER.  THEREFORE THE PROGRAM TERMINATES FOR THE USER'/' TO RESOLVE THE PROBLEM'/)
        !
        GO TO 1550
        !
        1370 WRITE(6,1380) KMAX,MEV
        1380 FORMAT(/' ALPHA,BETA FILE HEADER GIVES KMAX =',I6/&
        ' BUT EIGENVALUES WERE COMPUTED AT MEV = ',I6,' PROGRAM STOPS'/)
        !
        GO TO 1550
        !
        1390 WRITE(6,1400)
        1400 FORMAT(//' PROGRAM COMPUTED 1ST GUESSES AT T-MATRIX SIZES AND READ THEM TO'/&
        ' FILE 10, THEN TERMINATED AS REQUESTED.')
        GO TO 1550
        !
        1410 WRITE(6,1420) MTOL, MDIMTV
        1420 FORMAT(/' PROGRAM TERMINATES BECAUSE THE TVEC DIMENSION ANTICIPATED',I7/&
        '  IS LARGER THAN THE TVEC DIMENSION',I7,' SPECIFIED BY THE USER.'/&
        '  USER MAY RESET THE TVEC DIMENSION AND RESTART THE PROGRAM')
        GO TO 1550
        !
        1430 WRITE(6,1440)
        1440 FORMAT(/' PROGRAM TERMINATES BECAUSE NO SUITABLE T-EIGENVECTORS WERE IDENTIFIED'/&
        '  FOR ANY OF THE EIGENVALUES SUPPLIED.  PROBLEM COULD BE CAUSED'/&
        '  BY TOO SMALL A TVEC DIMENSION OR SIMPLY THAT SUITABLE T-VECTORS COULD'/&
        '  NOT BE IDENTIFIED.  USER SHOULD CHECK OUTPUT'/)
        GO TO 1550
        !
        1450 WRITE(6,1460) LVCONT,NTVEC,NGOOD
        1460 FORMAT(/' LVCONT FLAG =',I2,' AND NUMBER ',I5,' OF T-EIGENVECTORS COMPUTED N.E.'/&
        ' NUMBER',I5,' REQUESTED SO PROGRAM TERMINATES'/)
        GO TO 1550
        !
        1470 WRITE(6,1480)
        1480 FORMAT(//' PROGRAM TERMINATES WITHOUT COMPUTING RITZ VECTORS'/&
        ' BECAUSE ALL T-EIGENVECTORS WERE REJECTED AS NOT SUITABLE FOR THE RITZ VECTOR'/&
        ' COMPUTATIONS.  PROBABLE CAUSE IS LACK OF CONVERGENCE OF THE EIGENVALUES SUPPLIED'/)
        GO TO 1550
        !
        1490 WRITE(6,1500)
        1500 FORMAT(/' PROGRAM INDICATES THAT IT IS NOT POSSIBLE TO COMPUTE ANY OF THE'/&
        ' REQUESTED EIGENVECTORS. THEREFORE PROGRAM TERMINATES')
        DO 1510 J=1,NGOODC
          1510 IF(.NOT.silent_) WRITE(6,1520)  J,GOODEV(J),MP(J)
          1520 FORMAT(/4X,' J',11X,'GOODEV(J)',4X,'MP(J)'/I6,E20.12,I9)
          GO TO 1550

          1530 WRITE(6,1540) MBETA,KMAXN
          1540 FORMAT(/' PROGRAM TERMINATES BECAUSE THE STORAGE ALLOTTED FOR THE BETA ARRAY',I8/&
          ' IS NOT SUFFICIENT FOR THE ENLARGED KMAX =',I8,' THAT THE PROGRAM WANTS'/&
          ' USER CAN ENLARGE THE DIMENSIONS OF THE ALPHA AND BETA ARRAYS'/' AND RERUN THE PROGRAM'/)
 
          1550 CONTINUE
 
          IF(ALLOCATED(TVEC))   DEALLOCATE(TVEC)
          IF(ALLOCATED(V1))     DEALLOCATE(V1)
          IF(ALLOCATED(V2))     DEALLOCATE(V2)
          IF(ALLOCATED(ALPHA))  DEALLOCATE(ALPHA)
          IF(ALLOCATED(BETA))   DEALLOCATE(BETA)
          IF(ALLOCATED(G))      DEALLOCATE(G)
          IF(ALLOCATED(EVNEW))  DEALLOCATE(EVNEW)
          IF(ALLOCATED(TLAST))  DEALLOCATE(TLAST)
          IF(ALLOCATED(AMINGP)) DEALLOCATE(AMINGP)
          IF(ALLOCATED(TMINGP)) DEALLOCATE(TMINGP)
          IF(ALLOCATED(TERR))   DEALLOCATE(TERR)
          IF(ALLOCATED(ERR))    DEALLOCATE(ERR)
          IF(ALLOCATED(ERRDGP)) DEALLOCATE(ERRDGP)
          IF(ALLOCATED(RNORM))  DEALLOCATE(RNORM)
          IF(ALLOCATED(TBETA))  DEALLOCATE(TBETA)
          IF(ALLOCATED(MP))     DEALLOCATE(MP)
          IF(ALLOCATED(M1))     DEALLOCATE(M1)
          IF(ALLOCATED(M2))     DEALLOCATE(M2)
          IF(ALLOCATED(MA))     DEALLOCATE(MA)
          IF(ALLOCATED(ML))     DEALLOCATE(ML)
          IF(ALLOCATED(MINT))   DEALLOCATE(MINT)
          IF(ALLOCATED(MFIN))   DEALLOCATE(MFIN)
          IF(ALLOCATED(IDELTA)) DEALLOCATE(IDELTA)
          IF(ALLOCATED(SVSEED)) DEALLOCATE(SVSEED)
          IF(ALLOCATED(SVSOLD)) DEALLOCATE(SVSOLD)
          IF(ALLOCATED(RHSEED)) DEALLOCATE(RHSEED)
          IF(ALLOCATED(IIL))    DEALLOCATE(IIL)
          IF(ALLOCATED(IIX))    DEALLOCATE(IIX)

         IF(PRESENT(FILE2)) CLOSE(UNIT2_)
         IF(PRESENT(FILE3)) CLOSE(UNIT3_)
         IF(PRESENT(FILE4)) CLOSE(UNIT4_)
         IF(PRESENT(FILE5)) CLOSE(UNIT5_)
         IF(PRESENT(FILE10))CLOSE(UNIT10_)

     END subroutine

!**************************************************************************
!**************************************************************************
!**************************************************************************
!**************************************************************************
!**************************************************************************
!**************************************************************************
!**************************************************************************
!**************************************************************************

   END MODULE 


