#!/bin/bash

set -e # Exit on error
update_case_file 'write_params' F
update_case_file 'write_forces' F
update_case_file 'write_positions' F
update_case_file 'write_xyz' F
update_case_file 'write_density_plot' F
update_case_file 'write_ngwf_plot' F
update_case_file 'write_ngwf_grad_plot' F
update_case_file 'write_denskern' F
update_case_file 'write_tightbox_ngwfs' F
update_case_file 'write_converged_dk_ngwfs' F
update_case_file 'write_sw_ngwfs' F
update_case_file 'homo_plot' -1
update_case_file 'lumo_plot' -1
update_case_file 'dos_smear' 0.00 
# update_case_file 'ldos_smear' 0.00 
update_case_file 'ngwf_analysis' F
update_case_file 'popn_calculate' F
# update_case_file 'cond_calculate' F
update_case_file 'polarisation_calculate' F
update_case_file 'homo_dens_plot' -1
update_case_file 'lumo_dens_plot' -1
# update_case_file 'optics_energy_max' 0.00 
update_case_file 'cube_format' F
update_case_file 'grd_format' F
