#!/bin/bash

EXPECTED_ARGS=2

if [ $# -ne $EXPECTED_ARGS ]
then
  echo "Usage: `basename $0` ERROR expecting 2 arguments"
  echo "        1- the machine file name"
  echo "        2- the number of desired final processes"
  exit
fi

 nlines=`cat $1 |wc -l `

 #echo "N entries in file : " $nlines 
 nuniq=`cat $1 | sort |uniq |wc -l` 
 #echo " N entries for openmp : " $nuniq 

 #echo "you would like [x] entries : " $2
 ratio=`expr $2 / $nuniq ` 
 #echo " You need to duplicate the uniq entries [x] times :  " $ratio

 rm tmp_file 2>/dev/null
 for i in `seq 1 $ratio ` 
   do 
#  echo "duplicating entries"  
   cat $1 | uniq >> tmp_file 
  done 
  cat tmp_file | sort  > ${1}.dup
  rm tmp_file  
