#!/bin/bash

EXPECTED_ARGS=2

if [ $# -ne $EXPECTED_ARGS ]
then
  echo "Usage: `basename $0` ERROR merge_ac file1 [x] =number of up orbitals"
  exit
fi

if [ $2 == 6 ]
then
pr -m -t -s  ${1}1 ${1}2 | awk '{print $1 " " $2 " " $3  " "$4 " " $5 " " $6 " " $7 " " $9 " " $10 " " $11 " " $12 " " $13 " " $14 }' > $1 
fi

if [ $2 == 5 ]
then
pr -m -t -s  ${1}1 ${1}2 | awk '{print $1 " " $2 " " $3  " "$4 " " $5 " " $6     " " $8 " " $9 " " $10 " " $11 " " $12 }' > $1   
fi

if [ $2 == 4 ]
then
pr -m -t -s  ${1}1 ${1}2 | awk '{print $1 " " $2 " " $3  " "$4 " " $5    " " $7 " " $8 " " $9 " " $10 " " }' > $1
fi

if [ $2 == 3 ]
then
pr -m -t -s  ${1}1 ${1}2 | awk '{print $1 " " $2 " " $3  " "$4 " "    $6 " "  $7 " " $8 " " }' > $1
fi

if [ $2 == 2 ]
then
pr -m -t -s  ${1}1 ${1}2 | awk '{print $1 " " $2 " " $3  " " $5 " "  $6 " "  }' > $1
fi

if [ $2 == 1 ]
then
pr -m -t -s  ${1}1 ${1}2 | awk '{print $1 " " $2 " " $4 " "  }' > $1
fi



