#!/bin/bash
# Simple script for updating a variable entry in a ONETEP .dat file
# Written by Edward Linscott May 2019

# If an error occurs, exit immediately with an error code
set -e

variable="$1"
value="$2"
datfile="$(ls *.dat)"
updated_entry="$variable : $value"

# Find match, being careful to avoid partial matches (e.g. "ldos_smear" matching "dos_smear")
# In order to preserve double spacing, briefly reset IFS
IFS='%'
match=$(cat $datfile | awk -v var="$variable" -F" " '$1 == var')
n_matches=$(echo $match | wc -l)

if [ -z "$match" ]; then
   # For no matches, append to end of file
   echo $updated_entry >> $datfile
elif [ $n_matches -eq 1 ]; then
   # For one match, do in-place replacement
   sed -i "s/$match/$updated_entry/g" $datfile
else
   # For multiple matches, exit with error
   echo "ERROR: found multiple ($n_matches) entries for $variable in $datfile"
   # Restore IFS
   unset IFS
   exit 1
fi

# Print summary
echo "$variable set to $value in $datfile"

# Restore IFS
unset IFS
