#!/bin/bash
#            print "                    <<<<< CALCULATION SUMMARY >>>>>";

awk 'BEGIN {niter=0; brief=0; oldstep0=0;}
     /NGWF CG iteration  001/ {print "|ITER|    RMS GRADIENT   |     TOTAL ENERGY    |   step   |     Epredicted"};
     /Job started/ {printf "%s",$0; brief=0};
     /Job completed/ {printf "%s%s%s%s%s%s\n",$0," in ",TT," on ",NN," processors"};
     /TOTAL TIME/ {TT=$3; NN=$5};
     /Running on/ {printf " %s %s %s\n",$2,$3,$4};
     /RMS gradient/&&($0!~/Max/) {rmsgrad=$4;};
     /step 0/ {oldstep0=step0; step0=$6};
     /Selected quadratic step/ {step=$5};
     /Selected cubic step/ {step=$5};
     /Functional pred/ {pred=$4};
     /Starting BFGS iteration/||/improving iteration/ {step0=0; oldstep0=1};
     /NGWF line search finished/ {niter=niter+1;
        printf "%4d%21.14f%22.14f%11.6f%22.14f",niter,rmsgrad,step0,step,pred;
        if (step0>oldstep0) {printf "  +%16.14f!\n",step0-oldstep0} else {printf "\n"}};
     /RMS NGWF gradient =/ {rmsgrad=$6};
     /WARNING: slope along search direction is still positive/ {print}
     /WARNING: maximum number of NGWF CG iterations/ {message="  <-- MAXIT_NGWF_CG EXCEEDED"}
     /Wannier-like function optimisation converged/ {message="  <-- CG CONVERGED"}
     /NGWF self-consistent optimisation/ {brief=1;};
     (brief==0)&&/\-\- CG/ {niter=niter+1; 
                step0=$3; 
                printf "%4d%21.14f%22.14f%s\n",niter,rmsgrad,step0, message;
                niter=0};
     (brief==1)&&(NF>1)&&($0!~/[\|#=:(]/) {print $0; if($5~/CG/||$0~/Job started/) {brief=0}};
     /BFGS/&&($0!~/BFGS: line :/)&&($0!~/BFGS: trial:/)&&($0!~/BFGS: quad :/) {print};' $1
