#!/bin/bash
 rm dens1 dens2 dens5 dens7
for j in 1 2 5 7 ; do  for i in `seq 1 40` ; do k=`grep "total dens" sc_dmft_full_iter$i/onetep_dmft_part_solver_1_atom_${j} |awk '{print $4}'`; echo $i $k >> dens${j} ; done ; done ;
